package frc.robot.utils.path;

import choreo.Choreo;
import choreo.trajectory.SwerveSample;
import choreo.trajectory.Trajectory;
import frc.robot.autonomous.ChoreoTraj;
import frc.robot.utils.FieldInfo;

/**
 * Type-safe enum of pre-planned autonomous paths.
 *
 * <p>Each entry wraps a Choreo trajectory re-parameterized by arc-length for distance-based
 * following. Blue and red alliance variants are pre-computed at load time.
 *
 * <p>Entries reference {@link ChoreoTraj} constants generated by Choreo — if a trajectory is
 * deleted or renamed in Choreo, the constant disappears and this file fails to compile.
 *
 * <p>Usage:
 *
 * <pre>{@code
 * autoCommands.followPath(AutoPath.NEW_PATH);
 * }</pre>
 */
public enum AutoPath {
  NEW_PATH(ChoreoTraj.NewPath),
  ;

  private final ChoreoTraj choreoTraj;
  private final Trajectory<SwerveSample> trajectory;
  private final ArcLengthTrajectory blue;
  private final ArcLengthTrajectory red;

  AutoPath(ChoreoTraj choreoTraj) {
    this.choreoTraj = choreoTraj;
    this.trajectory =
        Choreo.<SwerveSample>loadTrajectory(choreoTraj.name())
            .orElseThrow(
                () ->
                    new RuntimeException(
                        "Failed to load Choreo trajectory: "
                            + choreoTraj.name()
                            + ". Ensure the .traj file exists in deploy/choreo/"));
    this.blue = ArcLengthTrajectory.fromChoreo(trajectory);
    this.red = ArcLengthTrajectory.fromChoreo(trajectory.flipped());
  }

  /**
   * Returns the alliance-appropriate arc-length trajectory.
   *
   * @return Blue trajectory on blue alliance, flipped trajectory on red alliance
   */
  public ArcLengthTrajectory get() {
    return FieldInfo.shouldFlip() ? red : blue;
  }

  /** Returns the raw Choreo trajectory (for reading event markers, etc.). */
  public Trajectory<SwerveSample> trajectory() {
    return trajectory;
  }

  /** Returns the underlying Choreo trajectory data (start/end poses, total time, etc.). */
  public ChoreoTraj choreoTraj() {
    return choreoTraj;
  }
}
