package frc.robot.utils.path;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.wpilibj.DriverStation;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.List;

/** Path constants generated by FRC Path Editor. */
public final class Paths {
  private Paths() {}

  public enum WaypointFlag {
    FEEDSHOOT("FeedShoot"),
    STOPSHOOT("StopShoot"),
    HUBSHOOT("HubShoot"),
    SLOWRAISEINTAKE("SlowRaiseIntake"),
    RUNINTAKE("RunIntake");

    private final String label;

    WaypointFlag(String label) {
      this.label = label;
    }

    public String label() {
      return label;
    }
  }

  // Named field positions
  public static final Pose2d START_LEFT =
      new Pose2d(
          new Translation2d(4.4474222222222215, 7.689296296296297), Rotation2d.fromDegrees(-90));
  public static final Pose2d START_LEFT_MIRROR =
      new Pose2d(
          new Translation2d(4.4474222222222215, 0.5207037037037034), Rotation2d.fromDegrees(90));
  public static final PathData START_LEFT_TO_RIGHT_TRENCH_TO_DEPOT =
      new PathData(
          List.of(
              new Translation2d(4.450453608247423, 7.694),
              new Translation2d(7.954546391752578, 7.024917525773197),
              new Translation2d(8.538724482791018, 4.0815082255037325),
              new Translation2d(7.732550650004322, 1.1087421816369574),
              new Translation2d(2.7696466040996435, 1.1860977045320782),
              new Translation2d(2.310484536082474, 6.598628865979382)),
          List.of(
              new PathData.HeadingWaypoint(0, Rotation2d.fromDegrees(-90)),
              new PathData.HeadingWaypoint(4, Rotation2d.fromDegrees(-180)),
              new PathData.HeadingWaypoint(2, Rotation2d.fromDegrees(-90)),
              new PathData.HeadingWaypoint(5, Rotation2d.fromDegrees(180)),
              new PathData.HeadingWaypoint(3, Rotation2d.fromDegrees(180))),
          VelocityConstraints.defaults()
              .withMaxVelocity(4.9)
              .withMaxAcceleration(10.791000000000002),
          List.of(
              new PathData.ConstraintZone(1, 2, 2, 10.791),
              new PathData.ConstraintZone(4, 5, 2, 10.791)),
          List.of(),
          List.of(
              new PathData.WaypointFlag("6804dfbe-520e-4ae6-929e-5df99023be6b", 1, "FeedShoot"),
              new PathData.WaypointFlag("0d5153d7-6868-4e5d-bdef-ed807b39e583", 3, "StopShoot"),
              new PathData.WaypointFlag("4dd5030e-828a-446d-b7b6-066c65094aaf", 4, "HubShoot")));

  public static final PathData START_LEFT_TO_RIGHT_BUMP =
      new PathData(
          List.of(
              new Translation2d(4.450453608247423, 7.694),
              new Translation2d(7.954546391752578, 7.024917525773197),
              new Translation2d(8.421157465509625, 4.047917648736876),
              new Translation2d(5.81031443298969, 2.6924),
              new Translation2d(3.0650154639175256, 3.162742268041238),
              new Translation2d(2.310484536082474, 6.598628865979382)),
          List.of(
              new PathData.HeadingWaypoint(0, Rotation2d.fromDegrees(-90)),
              new PathData.HeadingWaypoint(2, Rotation2d.fromDegrees(-90)),
              new PathData.HeadingWaypoint(5, Rotation2d.fromDegrees(0)),
              new PathData.HeadingWaypoint(3, Rotation2d.fromDegrees(-45)),
              new PathData.HeadingWaypoint(4, Rotation2d.fromDegrees(-45))),
          VelocityConstraints.defaults()
              .withMaxVelocity(4.9)
              .withMaxAcceleration(10.791000000000002),
          List.of(
              new PathData.ConstraintZone(1, 2, 2, 10.791),
              new PathData.ConstraintZone(4, 5, 2, 10.791),
              new PathData.ConstraintZone(3, 4, 1.67, 10.791)),
          List.of(),
          List.of(
              new PathData.WaypointFlag("cc4fa754-7892-4f4f-ba07-6097317818fa", 4, "HubShoot")));

  public static final PathData START_LEFT_TO_RIGHT_BUMP_LONG =
      new PathData(
          List.of(
              new Translation2d(4.450453608247423, 7.694),
              new Translation2d(7.954546391752578, 7.024917525773197),
              new Translation2d(8.421157465509625, 4.047917648736876),
              new Translation2d(5.81031443298969, 2.6924),
              new Translation2d(3.0650154639175256, 3.162742268041238),
              new Translation2d(2.391649007792475, 6.50002975271738),
              new Translation2d(3.5673191806064035, 7.524542344106494),
              new Translation2d(5.615748194014447, 7.53576883384933),
              new Translation2d(6.411051218398677, 6.605336071020213),
              new Translation2d(6.612797585865467, 3.4062153620647404),
              new Translation2d(5.991269349845201, 2.730804953560373),
              new Translation2d(2.952961816305469, 2.696666666666668)),
          List.of(
              new PathData.HeadingWaypoint(0, Rotation2d.fromDegrees(-90)),
              new PathData.HeadingWaypoint(2, Rotation2d.fromDegrees(-90)),
              new PathData.HeadingWaypoint(5, Rotation2d.fromDegrees(0)),
              new PathData.HeadingWaypoint(3, Rotation2d.fromDegrees(-45)),
              new PathData.HeadingWaypoint(4, Rotation2d.fromDegrees(-45)),
              new PathData.HeadingWaypoint(6, Rotation2d.fromDegrees(0)),
              new PathData.HeadingWaypoint(8, Rotation2d.fromDegrees(-90)),
              new PathData.HeadingWaypoint(10, Rotation2d.fromDegrees(45)),
              new PathData.HeadingWaypoint(11, Rotation2d.fromDegrees(45)),
              new PathData.HeadingWaypoint(7, Rotation2d.fromDegrees(0)),
              new PathData.HeadingWaypoint(9, Rotation2d.fromDegrees(-35)),
              new PathData.HeadingWaypoint(1, Rotation2d.fromDegrees(-90))),
          VelocityConstraints.defaults()
              .withMaxVelocity(4.9)
              .withMaxAcceleration(10.791000000000002),
          List.of(
              new PathData.ConstraintZone(1, 2, 2, 10.791),
              new PathData.ConstraintZone(4, 6, 1, 10.791),
              new PathData.ConstraintZone(3, 4, 1.67, 10.791),
              new PathData.ConstraintZone(10, 11, 1.67, 10.791),
              new PathData.ConstraintZone(8, 9, 2, 10.791)),
          List.of(),
          List.of(
              new PathData.WaypointFlag("0516a82a-73bc-4a6e-badb-5d448b866a7b", 1, "FeedShoot"),
              new PathData.WaypointFlag("cd1e38a2-db5d-44e2-97f6-07fee6e2fbe2", 2, "StopShoot"),
              new PathData.WaypointFlag("f6962919-e67d-4439-8f19-7aee94866e01", 4, "HubShoot"),
              new PathData.WaypointFlag("18825215-69a7-4de5-bd9b-bcf723a65c9a", 6, "StopShoot")));

  public static final PathData OP =
      new PathData(
          List.of(
              new Translation2d(4.4474222222222215, 7.689296296296297),
              new Translation2d(8.13522962962963, 7.11345925925926),
              new Translation2d(8.576296296296295, 4.8223629629629645),
              new Translation2d(5.795125925925926, 5.753503703703705),
              new Translation2d(3.4060148148148146, 5.839266666666668),
              new Translation2d(3.222237037037037, 7.5300222222222235),
              new Translation2d(6.064666666666666, 7.395251851851853),
              new Translation2d(6.113674074074074, 4.454807407407408),
              new Translation2d(7.4858814814814805, 4.8223629629629645),
              new Translation2d(6.848785185185185, 7.358496296296297),
              new Translation2d(3.0752148148148146, 7.554525925925927),
              new Translation2d(1.1149185185185184, 6.623385185185186),
              new Translation2d(1.0659111111111108, 5.630985185185186),
              new Translation2d(3.369259259259259, 7.566777777777778)),
          List.of(
              new PathData.HeadingWaypoint(1, Rotation2d.fromDegrees(270)),
              new PathData.HeadingWaypoint(3, Rotation2d.fromDegrees(315)),
              new PathData.HeadingWaypoint(2, Rotation2d.fromDegrees(270)),
              new PathData.HeadingWaypoint(4, Rotation2d.fromDegrees(315)),
              new PathData.HeadingWaypoint(6, Rotation2d.fromDegrees(0)),
              new PathData.HeadingWaypoint(5, Rotation2d.fromDegrees(0)),
              new PathData.HeadingWaypoint(9, Rotation2d.fromDegrees(180)),
              new PathData.HeadingWaypoint(10, Rotation2d.fromDegrees(180)),
              new PathData.HeadingWaypoint(7, Rotation2d.fromDegrees(270)),
              new PathData.HeadingWaypoint(8, Rotation2d.fromDegrees(85)),
              new PathData.HeadingWaypoint(11, Rotation2d.fromDegrees(205)),
              new PathData.HeadingWaypoint(13, Rotation2d.fromDegrees(180)),
              new PathData.HeadingWaypoint(0, Rotation2d.fromDegrees(-90))),
          VelocityConstraints.defaults()
              .withMaxVelocity(4.9)
              .withMaxAcceleration(10.791000000000002),
          List.of(
              new PathData.ConstraintZone(3, 4, 1.67, 10.791),
              new PathData.ConstraintZone(1, 2, 2.5, 10.791),
              new PathData.ConstraintZone(4, 5, 0.4, 10.791),
              new PathData.ConstraintZone(10, 13, 1.3, 10.791)),
          List.of(),
          List.of(
              new PathData.WaypointFlag("171ed5ba-6083-4aab-82bd-fd0e0e614390", 4, "HubShoot"),
              new PathData.WaypointFlag("ec2f238b-6e43-4cdf-93f4-f2703ab80ae6", 5, "StopShoot"),
              new PathData.WaypointFlag("7e5a241c-0a6f-4d8d-8e53-89f9b9e2be20", 10, "HubShoot"),
              new PathData.WaypointFlag(
                  "8f556a15-54ee-4d2c-9bd4-43ab6735bde0", 4, "SlowRaiseIntake"),
              new PathData.WaypointFlag("f24f6185-c700-4454-9f6c-a30e3af2e090", 6, "RunIntake"),
              new PathData.WaypointFlag(
                  "f9f15365-3bbe-4175-848b-efc574e2c984", 13, "SlowRaiseIntake")));

  public static final PathData OP_RIGHT =
      new PathData(
          List.of(
              new Translation2d(4.4474222222222215, 0.5207037037037034),
              new Translation2d(8.13522962962963, 1.0965407407407408),
              new Translation2d(8.576296296296295, 3.3876370370370363),
              new Translation2d(5.795125925925926, 2.4564962962962955),
              new Translation2d(3.4060148148148146, 2.370733333333333),
              new Translation2d(3.222237037037037, 0.6799777777777773),
              new Translation2d(6.064666666666666, 0.8147481481481478),
              new Translation2d(6.597223942208462, 2.9356346749226017),
              new Translation2d(7.851805985552115, 4.028059855521157)),
          List.of(
              new PathData.HeadingWaypoint(0, Rotation2d.fromDegrees(90)),
              new PathData.HeadingWaypoint(1, Rotation2d.fromDegrees(90)),
              new PathData.HeadingWaypoint(3, Rotation2d.fromDegrees(45)),
              new PathData.HeadingWaypoint(2, Rotation2d.fromDegrees(90)),
              new PathData.HeadingWaypoint(4, Rotation2d.fromDegrees(45)),
              new PathData.HeadingWaypoint(6, Rotation2d.fromDegrees(0)),
              new PathData.HeadingWaypoint(5, Rotation2d.fromDegrees(0)),
              new PathData.HeadingWaypoint(7, Rotation2d.fromDegrees(90)),
              new PathData.HeadingWaypoint(13, Rotation2d.fromDegrees(180))),
          VelocityConstraints.defaults()
              .withMaxVelocity(4.9)
              .withMaxAcceleration(10.791000000000002),
          List.of(
              new PathData.ConstraintZone(3, 4, 1.67, 10.791),
              new PathData.ConstraintZone(1, 2, 3, 10.791),
              new PathData.ConstraintZone(4, 5, 0.6, 10.791)),
          List.of(),
          List.of(
              new PathData.WaypointFlag("a93d03e8-e085-4640-b510-ab1fbd36c6ee", 4, "HubShoot"),
              new PathData.WaypointFlag("28221e58-5585-4c36-ba49-cd43d20e7d6e", 5, "StopShoot")));

  public static final PathData SHARK =
      new PathData(
          List.of(
              new Translation2d(4.419906753471135, 7.586285106050246),
              new Translation2d(8.135246452913565, 6.874017890480497),
              new Translation2d(8.481754818664674, 4.621713452057237),
              new Translation2d(7.884990410982211, 4.39070786862921),
              new Translation2d(6.96096810231259, 5.064474153627621),
              new Translation2d(7.730986692870608, 6.181001140196417),
              new Translation2d(8.597257607248377, 5.584236716340682),
              new Translation2d(7.82723901669036, 5.218477875912972),
              new Translation2d(6.4989569479777805, 7.393780453193557),
              new Translation2d(4.342904894415334, 7.624786036621583),
              new Translation2d(0.8778212369042575, 7.624786036621583)),
          List.of(
              new PathData.HeadingWaypoint(0, Rotation2d.fromDegrees(-90)),
              new PathData.HeadingWaypoint(1, Rotation2d.fromDegrees(-90)),
              new PathData.HeadingWaypoint(2, Rotation2d.fromDegrees(-130)),
              new PathData.HeadingWaypoint(3, Rotation2d.fromDegrees(-200)),
              new PathData.HeadingWaypoint(5, Rotation2d.fromDegrees(-5)),
              new PathData.HeadingWaypoint(6, Rotation2d.fromDegrees(-90)),
              new PathData.HeadingWaypoint(7, Rotation2d.fromDegrees(-180)),
              new PathData.HeadingWaypoint(8, Rotation2d.fromDegrees(-180)),
              new PathData.HeadingWaypoint(9, Rotation2d.fromDegrees(-180))),
          VelocityConstraints.defaults()
              .withMaxVelocity(4.9)
              .withMaxAcceleration(10.791000000000002),
          List.of(
              new PathData.ConstraintZone(1, 7, 2, 10.791),
              new PathData.ConstraintZone(9, 10, 1.5, 10.791)),
          List.of(),
          List.of(
              new PathData.WaypointFlag("7982971e-c96d-4907-ae7a-6239c3c2446e", 1, "FeedShoot"),
              new PathData.WaypointFlag("94e22bd0-704b-4db3-970a-2491db98897f", 7, "StopShoot"),
              new PathData.WaypointFlag("b5ab820f-bd0a-465d-86d4-c33f8607c481", 9, "HubShoot")));

  /**
   * Returns the path mirrored for the red alliance if needed. Call during autonomousInit() or later
   * when the alliance is known.
   */
  public static PathData forAlliance(PathData path) {
    var alliance = DriverStation.getAlliance();
    if (alliance.isPresent() && alliance.get() == DriverStation.Alliance.Red) {
      return path.mirrorForRedAlliance();
    }
    return path;
  }

  /** Returns the constant name for a path declared in this class. */
  public static String nameOf(PathData path) {
    for (Field field : Paths.class.getDeclaredFields()) {
      if (field.getType() != PathData.class
          || !Modifier.isStatic(field.getModifiers())
          || !Modifier.isPublic(field.getModifiers())) {
        continue;
      }

      try {
        if (field.get(null) == path) {
          return field.getName();
        }
      } catch (IllegalAccessException e) {
        throw new IllegalStateException("Unable to read path constant: " + field.getName(), e);
      }
    }

    throw new IllegalArgumentException("Path is not a named constant in Paths");
  }
}
