package frc.robot.utils.path;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.wpilibj.DriverStation;
import java.util.List;

/** Path constants generated by FRC Path Editor. */
public final class Paths {
  private Paths() {}

  // Named field positions
  public static final Pose2d CENTER_BEFORE_BALLS =
      new Pose2d(
          new Translation2d(7.982812808403318, 7.114796939376104), Rotation2d.fromDegrees(-100));
  public static final Pose2d CENTER_BEFORE_BALLS_MIRROR =
      new Pose2d(
          new Translation2d(7.982812808403318, 1.0952030606238967), Rotation2d.fromDegrees(100));
  public static final Pose2d CENTER_CENTER =
      new Pose2d(
          new Translation2d(8.654537305316397, 4.61773396115362), Rotation2d.fromDegrees(-100));
  public static final Pose2d CENTER_CENTER_MIRROR =
      new Pose2d(
          new Translation2d(8.654537305316397, 3.5922660388463807), Rotation2d.fromDegrees(100));
  public static final Pose2d START =
      new Pose2d(
          new Translation2d(4.448957846382339, 7.5820835785756335), Rotation2d.fromDegrees(-90));
  public static final Pose2d START_MIRROR =
      new Pose2d(
          new Translation2d(4.448957846382339, 0.6279164214243673), Rotation2d.fromDegrees(90));
  public static final PathData LEFT =
      new PathData(
          List.of(
              new Translation2d(4.448957846382339, 7.5820835785756335),
              new Translation2d(7.982812808403318, 7.114796939376104),
              new Translation2d(8.654537305316397, 4.61773396115362)),
          List.of(
              new PathData.HeadingWaypoint(2, Rotation2d.fromDegrees(-100)),
              new PathData.HeadingWaypoint(1, Rotation2d.fromDegrees(-100)),
              new PathData.HeadingWaypoint(0, Rotation2d.fromDegrees(-90))),
          VelocityConstraints.defaults().withMaxVelocity(5).withMaxAcceleration(10.791),
          List.of(new PathData.ConstraintZone(1, 2, 2, 10.791)),
          List.of());

  public static final PathData RIGHT =
      new PathData(
          List.of(
              new Translation2d(4.448957846382339, 0.6279164214243673),
              new Translation2d(7.982812808403318, 1.0952030606238967),
              new Translation2d(8.654537305316397, 3.5922660388463807)),
          List.of(
              new PathData.HeadingWaypoint(2, Rotation2d.fromDegrees(100)),
              new PathData.HeadingWaypoint(1, Rotation2d.fromDegrees(100)),
              new PathData.HeadingWaypoint(0, Rotation2d.fromDegrees(90))),
          VelocityConstraints.defaults().withMaxVelocity(5).withMaxAcceleration(10.791),
          List.of(new PathData.ConstraintZone(1, 2, 2, 10.791)),
          List.of());

  /**
   * Returns the path mirrored for the red alliance if needed. Call during autonomousInit() or later
   * when the alliance is known.
   */
  public static PathData forAlliance(PathData path) {
    var alliance = DriverStation.getAlliance();
    if (alliance.isPresent() && alliance.get() == DriverStation.Alliance.Red) {
      return path.mirrorForRedAlliance();
    }
    return path;
  }
}
